// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWzY60X918-N_P5fSFQ2oDc1Q5FWEvdHk',
    appId: '1:255778525123:web:330fe04341aa35b7e0b776',
    messagingSenderId: '255778525123',
    projectId: 'edoxlibrary',
    authDomain: 'edoxlibrary.firebaseapp.com',
    storageBucket: 'edoxlibrary.firebasestorage.app',
    measurementId: 'G-NTVLKWT3YW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfiw0ge9jNUDQW3d4V18K-UXP28IqhfnM',
    appId: '1:255778525123:android:27b3343284352f26e0b776',
    messagingSenderId: '255778525123',
    projectId: 'edoxlibrary',
    storageBucket: 'edoxlibrary.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0f-MkoIWQmvCeDvGd5qvrwvmZAesH-Z4',
    appId: '1:255778525123:ios:64518716a136eecee0b776',
    messagingSenderId: '255778525123',
    projectId: 'edoxlibrary',
    storageBucket: 'edoxlibrary.firebasestorage.app',
    iosBundleId: 'com.edox.library',
  );
}
